services:
  postgres:
    image: postgres:16
    container_name: mossaq_db
    environment:
      POSTGRES_DB: mossaq
      POSTGRES_USER: mossaq_user
      POSTGRES_PASSWORD: mossaq_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: