version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mossaq-db
    environment:
      POSTGRES_DB: mossaq
      POSTGRES_USER: mossaq_user
      POSTGRES_PASSWORD: mossaq_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: